services:

  mtg:
    container_name: "magic-gathering-api"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - magic-gathering-api
    ports:
      - "3000:3000"

  db_mtg:
    container_name: "magic-gathering-api"
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: 'project_card_game'
      MONGO_INITDB_ROOT_USERNAME: 'magic-gathering-api'
      MONGO_INITDB_ROOT_PASSWORD: 'magic-gathering-api'
